#!/bin/bash

LOG_FILE="/tmp/1672396-linux-monitoring-database-query-performance/db_queries.log"

awk '
BEGIN { RS=""; count=0 }
/[0-9]+\n[0-9a-fA-F\-]+\n[0-9]+ +SUCCESS/ {
  # Get execution time and status
  split($0, lines, "\n")
  split(lines[3], parts, " ")
  exec_time = parts[1]
  status = parts[2]

  gsub(/^ +| +$/, "", status)

  if (status == "SUCCESS" && exec_time > 2000) {
    count++
  }
}
END { print count }
' "$LOG_FILE"